sudo: required
dist: xenial
env:
- PY=e ANGR_ROOT=~/angr-dev
install:
- sudo apt-get update
- pushd ~
- git clone -q https://github.com/angr/angr-dev
- cd angr-dev
- export VIRTUALENVWRAPPER_PYTHON=$(pyenv which python3)
- ./setup.sh -i -w -b "$BRANCH" -"$PY" angr -s -c -C
- sudo apt-get install -y python3 python3-pip hugo python3-venv
- popd
- make install && make public
script: make build
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_9ea4008c5d51_key -iv $encrypted_9ea4008c5d51_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa
